name: leaf_morpho_tools-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - opencv
  - pyzbar
  - roboflow
  - tqdm
  - scipy
  - qreader
  - pip
  - pip:
      - roboflow
      - qreader
